# Generated by Django 4.2.17 on 2025-01-09 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoglioCatastale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice_foglio", models.CharField(max_length=50, unique=True)),
                (
                    "nome_foglio",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("comune", models.CharField(max_length=100)),
                ("geojson_perimetro", models.JSONField()),
                ("geojson_edifici", models.JSONField()),
                (
                    "data_creazione",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_modifica", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
