# Generated by Django 4.2.17 on 2025-01-09 15:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Edificio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indirizzo", models.CharField(max_length=255)),
                (
                    "coordinate",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("codice_catastale", models.CharField(max_length=50, unique=True)),
                ("tipo_edificio", models.CharField(max_length=50)),
            ],
        ),
    ]
