# Generated by Django 4.2.17 on 2025-01-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpatialRefSys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("srid", models.IntegerField()),
                ("auth_name", models.CharField(max_length=205)),
                ("auth_srid", models.IntegerField()),
                ("srtext", models.TextField()),
                ("proj4text", models.TextField()),
            ],
        ),
    ]
